# Autogenerated wrapper script for BEDTools_jll for x86_64-linux-musl-cxx11
export bedtools

using CompilerSupportLibraries_jll
using Zlib_jll
using Bzip2_jll
using XZ_jll
JLLWrappers.@generate_wrapper_header("BEDTools")
JLLWrappers.@declare_executable_product(bedtools)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll, Bzip2_jll, XZ_jll)
    JLLWrappers.@init_executable_product(
        bedtools,
        "bin/bedtools",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
